export const ADD_TODO = "ADD_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const EDIT_TODO = "EDIT_TODO";
export const COMPLETE_TODO = "COMPLETE_TODO";
export const COMPLETE_ALL_TODOS = "COMPLETE_ALL_TODOS";
export const CLEAR_COMPLETED = "CLEAR_COMPLETED";
export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";

export const ADD_EXPERIMENT = "ADD_EXPERIMENT";
export const GET_ALL_EXPERIMENT = "GET_ALL_EXPERIMENT";

export const START_EXPERIMENT = "START_EXPERIMENT";
export const RESET_EXPERIMENT = "RESET_EXPERIMENT";
