export const ADD_EXPERIMENT = "ADD_EXPERIMENT";
export const GET_ALL_EXPERIMENT = "GET_ALL_EXPERIMENT";

export const START_EXPERIMENT = "START_EXPERIMENT";
export const RESET_EXPERIMENT = "RESET_EXPERIMENT";
